### ISSUE TITLE
认领翻译 “Active Support 核心扩展” 

### ISSUE THREAD

**Issue by algo31031** [ruby-china/guides#13]
fork了一份开始翻译“Active Support 核心扩展”这段，但是进展缓慢。

按目前速度这周恐怕都难翻完，@Andor_Chen自己一人搞定了那么多，这是何等大爱呀...

**Comment by JuanitoFatas** [comment]
Closed by https://github.com/ruby-china/guides/pull/18, awesome work @algo31031 !!! :+1:
