### ISSUE TITLE
教程中删除博客评论的语句有问题

### ISSUE THREAD

**Issue by lvzhongyi** [ruby-china/guides#39]
你好
　　　不知道是我的版本和你的不一样还是一些其它原因，在删除博客评论这一句，在我这边是显示报错的，我检查过，其它功能都是正常的，      <%= link_to 'Destroy Comment'，[comment.article,comment],method: :delete,data: { confirm: 'Are you sure?' } %>，我使用的ruby 版本是2.2.0，rails 版本是4.2.0，编辑器是RubyMine，ubuntu环境下工作

**Comment by JuanitoFatas** [comment]
Please ask on [ruby-china](https://ruby-china.org/topics/new).
