### ISSUE TITLE
Active Record Validations 这章的Validations Overview 节的部分翻译值得商量。 

### ISSUE THREAD

**Issue by CCLink2008** [ruby-china/guides#44]
As you can see, our validation lets us know that our Person is not valid without a name attribute. The second Person will not be persisted to the database.
（如上所示，如果 Person 没有 name 属性，验证就会将其视为不合法对象。创建的第二个 Person 对象不会存入数据库。）
其实英文里面的意思是说Person的name属性字段不允许为空值，而不是没有属性吧。是否可以改成“如果Person的name属性没被赋值”呢？

**Comment by JuanitoFatas** [comment]
請送 Pull Request : )
