### ISSUE TITLE
调试rails程序-2.2日志等级说明小错误

### ISSUE THREAD

**Issue by james-gone** [ruby-china/guides#61]
当前文字：Rails 为生产环境设置的默认日志等级是 info，生产环境和测试环境的默认日志等级是 debug。
应该为：Rails 为生产环境设置的默认日志等级是 info，开发环境和测试环境的默认日志等级是 debug。

**Comment by james-gone** [comment]
当前的调试说明，2.2 Log Levels内已经更改为：
The default Rails log level is debug in all environments.
默认的Rails log级别在所有环境都是 debug.

**Comment by JuanitoFatas** [comment]
Pull Request is welcome.
